# Generated by Django 4.2.16 on 2024-10-19 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('club_id', models.AutoField(primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=50)),
                ('club_establishedDate', models.DateField(blank=True, null=True)),
                ('club_slogan', models.CharField(blank=True, max_length=255, null=True)),
                ('club_description', models.TextField(blank=True, max_length=5000, null=True)),
                ('club_imgUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('club_logoUrl', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'CLUB_INFOR',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.AutoField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'DEPARTMENT',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('member_avaUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('member_name', models.CharField(max_length=50)),
                ('member_dob', models.DateField()),
                ('member_phoneNum', models.CharField(max_length=11)),
                ('member_addr', models.CharField(blank=True, max_length=100, null=True)),
                ('member_class', models.CharField(max_length=10)),
                ('member_joinedDate', models.DateField()),
                ('member_accPassword', models.CharField(max_length=255)),
                ('member_accStatus', models.IntegerField()),
                ('member_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
            ],
            options={
                'db_table': 'MEMBER',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=30)),
                ('post_subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('post_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('post_postedDate', models.DateField()),
                ('post_numOfLike', models.IntegerField(default=0)),
                ('post_numOfComment', models.IntegerField(default=0)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
            options={
                'db_table': 'POST',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'ROLE',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TASK_STATUS',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=30)),
                ('task_subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('task_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('task_startDate', models.DateField()),
                ('task_dueDate', models.DateField()),
                ('task_note', models.CharField(blank=True, max_length=50, null=True)),
                ('task_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.taskstatus')),
            ],
            options={
                'db_table': 'TASK',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='member_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.role'),
        ),
        migrations.CreateModel(
            name='CommentOfPost',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=200)),
                ('comment_createdDate', models.DateField()),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
            options={
                'db_table': 'COMMENT_OF_POST',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_title', models.CharField(max_length=30)),
                ('activity_subtitle', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_content', models.TextField(blank=True, max_length=1000, null=True)),
                ('activity_postedDate', models.DateField()),
                ('activity_thumbnailUrl', models.CharField(blank=True, max_length=255, null=True)),
                ('activity_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
            options={
                'db_table': 'ACTIVITY',
            },
        ),
        migrations.CreateModel(
            name='LikeOfPost',
            fields=[
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.post')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.member')),
            ],
            options={
                'db_table': 'LIKE_OF_POST',
                'unique_together': {('post_id', 'member_id')},
            },
        ),
    ]
